"""Added column for quesion and answer models

Revision ID: 005f5d103e4e
Revises: b4112b4539d7
Create Date: 2024-04-23 02:39:28.509135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005f5d103e4e'
down_revision: Union[str, None] = 'b4112b4539d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
