"""Added admin model

Revision ID: 3725fb9c0b78
Revises: ba5797397cc5
Create Date: 2024-04-21 18:46:27.961277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3725fb9c0b78'
down_revision: Union[str, None] = 'ba5797397cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.CHAR(length=20), nullable=True))
    op.add_column('admins', sa.Column('password', sa.CHAR(length=20), nullable=True))
    op.create_unique_constraint(None, 'admins', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'password')
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###
