"""Add answer model

Revision ID: b4112b4539d7
Revises: c5d5474653f1
Create Date: 2024-04-22 11:00:49.151979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4112b4539d7'
down_revision: Union[str, None] = 'c5d5474653f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.BigInteger(), nullable=False))
    op.add_column('answers', sa.Column('answer', sa.String(), nullable=False))
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_unique_constraint(None, 'answers', ['answer'])
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.drop_constraint('questions_theme_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_theme_id_fkey', 'questions', 'themes', ['theme_id'], ['id'])
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='unique')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_column('answers', 'is_correct')
    op.drop_column('answers', 'answer')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
