"""Added question model

Revision ID: c5d5474653f1
Revises: 3725fb9c0b78
Create Date: 2024-04-21 20:15:25.227755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d5474653f1'
down_revision: Union[str, None] = '3725fb9c0b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'email',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('admins', 'password',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.add_column('questions', sa.Column('theme_id', sa.BigInteger(), nullable=False))
    op.add_column('questions', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'questions', ['title'])
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'])
    op.add_column('themes', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'themes', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_column('themes', 'title')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'title')
    op.drop_column('questions', 'theme_id')
    op.alter_column('admins', 'password',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('admins', 'email',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
